const temporalData = [
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
  {
    lolName: '아이언포우',
    favorPosition: '정글',
    tier: 'Platinum',
    win: 100,
    lose: 50,
    kill: 100,
    death: 50,
    assist: 100,
    validTime: 300,
    mike: true,
    title: '칼바람 할사람',
    content:
      '나랑 칼바람 할사람? kda랑 비슷하다고 생각하면 된다. 질문있으면 받는다.',
  },
];
export default temporalData;
